version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fitcheck
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - fitcheck-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fitcheck
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fitcheck-network

  celery_worker:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fitcheck
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - fitcheck-network

  celery_beat:
    build: .
    command: celery -A app.tasks beat --loglevel=info
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fitcheck
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    networks:
      - fitcheck-network

volumes:
  postgres_data:
  redis_data:

networks:
  fitcheck-network:
    driver: bridge
